// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ClassEnmity_Config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ConfigData {

  /// <summary>Holder for reflection information generated from ClassEnmity_Config.proto</summary>
  public static partial class ClassEnmityConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for ClassEnmity_Config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClassEnmityConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhDbGFzc0VubWl0eV9Db25maWcucHJvdG8SCkNvbmZpZ0RhdGEiVwoSQ2xh",
            "c3NFbm1pdHlfQ29uZmlnEgoKAmlkGAEgASgNEgwKBGZyb20YAiABKA0SDAoE",
            "ZGVzYxgDIAEoCRIKCgJ0bxgEIAEoDRINCgV2YWx1ZRgFIAEoBSLbAQoXQ2xh",
            "c3NFbm1pdHlfQ29uZmlnX0RhdGESYQoYQ2xhc3NFbm1pdHlfQ29uZmlnX2l0",
            "ZW1zGAEgAygLMj8uQ29uZmlnRGF0YS5DbGFzc0VubWl0eV9Db25maWdfRGF0",
            "YS5DbGFzc0VubWl0eUNvbmZpZ0l0ZW1zRW50cnkaXQobQ2xhc3NFbm1pdHlD",
            "b25maWdJdGVtc0VudHJ5EgsKA2tleRgBIAEoDRItCgV2YWx1ZRgCIAEoCzIe",
            "LkNvbmZpZ0RhdGEuQ2xhc3NFbm1pdHlfQ29uZmlnOgI4AUIjCiFjb20udHJp",
            "bml0aWdhbWVzLnNlcnZlci5jb25mLmF1dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ConfigData.ClassEnmity_Config), global::ConfigData.ClassEnmity_Config.Parser, new[]{ "Id", "From", "Desc", "To", "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ConfigData.ClassEnmity_Config_Data), global::ConfigData.ClassEnmity_Config_Data.Parser, new[]{ "ClassEnmityConfigItems" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClassEnmity_Config : pb::IMessage<ClassEnmity_Config> {
    private static readonly pb::MessageParser<ClassEnmity_Config> _parser = new pb::MessageParser<ClassEnmity_Config>(() => new ClassEnmity_Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClassEnmity_Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ConfigData.ClassEnmityConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClassEnmity_Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClassEnmity_Config(ClassEnmity_Config other) : this() {
      id_ = other.id_;
      from_ = other.from_;
      desc_ = other.desc_;
      to_ = other.to_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClassEnmity_Config Clone() {
      return new ClassEnmity_Config(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    /// <summary>
    ///* id 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "from" field.</summary>
    public const int FromFieldNumber = 2;
    private uint from_;
    /// <summary>
    ///* 兵种 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint From {
      get { return from_; }
      set {
        from_ = value;
      }
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 3;
    private string desc_ = "";
    /// <summary>
    ///* 描述 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "to" field.</summary>
    public const int ToFieldNumber = 4;
    private uint to_;
    /// <summary>
    ///* 接受仇恨兵种 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint To {
      get { return to_; }
      set {
        to_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 5;
    private int value_;
    /// <summary>
    ///* 初始仇恨 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClassEnmity_Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClassEnmity_Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (From != other.From) return false;
      if (Desc != other.Desc) return false;
      if (To != other.To) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (From != 0) hash ^= From.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (To != 0) hash ^= To.GetHashCode();
      if (Value != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (From != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(From);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Desc);
      }
      if (To != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(To);
      }
      if (Value != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (From != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(From);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (To != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(To);
      }
      if (Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClassEnmity_Config other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.From != 0) {
        From = other.From;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.To != 0) {
        To = other.To;
      }
      if (other.Value != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 16: {
            From = input.ReadUInt32();
            break;
          }
          case 26: {
            Desc = input.ReadString();
            break;
          }
          case 32: {
            To = input.ReadUInt32();
            break;
          }
          case 40: {
            Value = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ClassEnmity_Config_Data : pb::IMessage<ClassEnmity_Config_Data> {
    private static readonly pb::MessageParser<ClassEnmity_Config_Data> _parser = new pb::MessageParser<ClassEnmity_Config_Data>(() => new ClassEnmity_Config_Data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClassEnmity_Config_Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ConfigData.ClassEnmityConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClassEnmity_Config_Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClassEnmity_Config_Data(ClassEnmity_Config_Data other) : this() {
      classEnmityConfigItems_ = other.classEnmityConfigItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClassEnmity_Config_Data Clone() {
      return new ClassEnmity_Config_Data(this);
    }

    /// <summary>Field number for the "ClassEnmity_Config_items" field.</summary>
    public const int ClassEnmityConfigItemsFieldNumber = 1;
    private static readonly pbc::MapField<uint, global::ConfigData.ClassEnmity_Config>.Codec _map_classEnmityConfigItems_codec
        = new pbc::MapField<uint, global::ConfigData.ClassEnmity_Config>.Codec(pb::FieldCodec.ForUInt32(8), pb::FieldCodec.ForMessage(18, global::ConfigData.ClassEnmity_Config.Parser), 10);
    private readonly pbc::MapField<uint, global::ConfigData.ClassEnmity_Config> classEnmityConfigItems_ = new pbc::MapField<uint, global::ConfigData.ClassEnmity_Config>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<uint, global::ConfigData.ClassEnmity_Config> ClassEnmityConfigItems {
      get { return classEnmityConfigItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClassEnmity_Config_Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClassEnmity_Config_Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!ClassEnmityConfigItems.Equals(other.ClassEnmityConfigItems)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= ClassEnmityConfigItems.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      classEnmityConfigItems_.WriteTo(output, _map_classEnmityConfigItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += classEnmityConfigItems_.CalculateSize(_map_classEnmityConfigItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClassEnmity_Config_Data other) {
      if (other == null) {
        return;
      }
      classEnmityConfigItems_.Add(other.classEnmityConfigItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            classEnmityConfigItems_.AddEntriesFrom(input, _map_classEnmityConfigItems_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
