// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Dispose_Config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ConfigData {

  /// <summary>Holder for reflection information generated from Dispose_Config.proto</summary>
  public static partial class DisposeConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for Dispose_Config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DisposeConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChREaXNwb3NlX0NvbmZpZy5wcm90bxIKQ29uZmlnRGF0YSJGCg5EaXNwb3Nl",
            "X0NvbmZpZxIKCgJpZBgBIAEoDRILCgNudW0YAiABKA0SDAoEbGFuZBgEIAEo",
            "DRINCgVzY2VuZRgFIAMoDSLDAQoTRGlzcG9zZV9Db25maWdfRGF0YRJVChRE",
            "aXNwb3NlX0NvbmZpZ19pdGVtcxgBIAMoCzI3LkNvbmZpZ0RhdGEuRGlzcG9z",
            "ZV9Db25maWdfRGF0YS5EaXNwb3NlQ29uZmlnSXRlbXNFbnRyeRpVChdEaXNw",
            "b3NlQ29uZmlnSXRlbXNFbnRyeRILCgNrZXkYASABKA0SKQoFdmFsdWUYAiAB",
            "KAsyGi5Db25maWdEYXRhLkRpc3Bvc2VfQ29uZmlnOgI4AUIjCiFjb20udHJp",
            "bml0aWdhbWVzLnNlcnZlci5jb25mLmF1dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ConfigData.Dispose_Config), global::ConfigData.Dispose_Config.Parser, new[]{ "Id", "Num", "Land", "Scene" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ConfigData.Dispose_Config_Data), global::ConfigData.Dispose_Config_Data.Parser, new[]{ "DisposeConfigItems" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Dispose_Config : pb::IMessage<Dispose_Config> {
    private static readonly pb::MessageParser<Dispose_Config> _parser = new pb::MessageParser<Dispose_Config>(() => new Dispose_Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Dispose_Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ConfigData.DisposeConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Dispose_Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Dispose_Config(Dispose_Config other) : this() {
      id_ = other.id_;
      num_ = other.num_;
      land_ = other.land_;
      scene_ = other.scene_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Dispose_Config Clone() {
      return new Dispose_Config(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    /// <summary>
    ///* 编号 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private uint num_;
    /// <summary>
    ///* 最大人数 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    /// <summary>Field number for the "land" field.</summary>
    public const int LandFieldNumber = 4;
    private uint land_;
    /// <summary>
    ///* 所属大陆 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Land {
      get { return land_; }
      set {
        land_ = value;
      }
    }

    /// <summary>Field number for the "scene" field.</summary>
    public const int SceneFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_scene_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> scene_ = new pbc::RepeatedField<uint>();
    /// <summary>
    ///* 编辑场景 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> Scene {
      get { return scene_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Dispose_Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Dispose_Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Num != other.Num) return false;
      if (Land != other.Land) return false;
      if(!scene_.Equals(other.scene_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Num != 0) hash ^= Num.GetHashCode();
      if (Land != 0) hash ^= Land.GetHashCode();
      hash ^= scene_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Num);
      }
      if (Land != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Land);
      }
      scene_.WriteTo(output, _repeated_scene_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Num);
      }
      if (Land != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Land);
      }
      size += scene_.CalculateSize(_repeated_scene_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Dispose_Config other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Num != 0) {
        Num = other.Num;
      }
      if (other.Land != 0) {
        Land = other.Land;
      }
      scene_.Add(other.scene_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 16: {
            Num = input.ReadUInt32();
            break;
          }
          case 32: {
            Land = input.ReadUInt32();
            break;
          }
          case 42:
          case 40: {
            scene_.AddEntriesFrom(input, _repeated_scene_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Dispose_Config_Data : pb::IMessage<Dispose_Config_Data> {
    private static readonly pb::MessageParser<Dispose_Config_Data> _parser = new pb::MessageParser<Dispose_Config_Data>(() => new Dispose_Config_Data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Dispose_Config_Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ConfigData.DisposeConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Dispose_Config_Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Dispose_Config_Data(Dispose_Config_Data other) : this() {
      disposeConfigItems_ = other.disposeConfigItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Dispose_Config_Data Clone() {
      return new Dispose_Config_Data(this);
    }

    /// <summary>Field number for the "Dispose_Config_items" field.</summary>
    public const int DisposeConfigItemsFieldNumber = 1;
    private static readonly pbc::MapField<uint, global::ConfigData.Dispose_Config>.Codec _map_disposeConfigItems_codec
        = new pbc::MapField<uint, global::ConfigData.Dispose_Config>.Codec(pb::FieldCodec.ForUInt32(8), pb::FieldCodec.ForMessage(18, global::ConfigData.Dispose_Config.Parser), 10);
    private readonly pbc::MapField<uint, global::ConfigData.Dispose_Config> disposeConfigItems_ = new pbc::MapField<uint, global::ConfigData.Dispose_Config>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<uint, global::ConfigData.Dispose_Config> DisposeConfigItems {
      get { return disposeConfigItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Dispose_Config_Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Dispose_Config_Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!DisposeConfigItems.Equals(other.DisposeConfigItems)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= DisposeConfigItems.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      disposeConfigItems_.WriteTo(output, _map_disposeConfigItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += disposeConfigItems_.CalculateSize(_map_disposeConfigItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Dispose_Config_Data other) {
      if (other == null) {
        return;
      }
      disposeConfigItems_.Add(other.disposeConfigItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            disposeConfigItems_.AddEntriesFrom(input, _map_disposeConfigItems_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
