// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorldMap_Config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ConfigData {

  /// <summary>Holder for reflection information generated from WorldMap_Config.proto</summary>
  public static partial class WorldMapConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for WorldMap_Config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorldMapConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVXb3JsZE1hcF9Db25maWcucHJvdG8SCkNvbmZpZ0RhdGEi7AEKD1dvcmxk",
            "TWFwX0NvbmZpZxIKCgJpZBgBIAEoDRIUCgxiYW5rX2RlZmF1bHQYAyABKAkS",
            "EwoLY29uZGl0aW9uX2EYBCABKAkSDgoGYmFua19hGAUgASgJEhMKC2NvbmRp",
            "dGlvbl9iGAYgASgJEg4KBmJhbmtfYhgHIAEoCRITCgtjb25kaXRpb25fYxgI",
            "IAEoCRIOCgZiYW5rX2MYCSABKAkSEwoLY29uZGl0aW9uX2QYCiABKAkSDgoG",
            "YmFua19kGAsgASgJEhMKC2NvbmRpdGlvbl9lGAwgASgJEg4KBmJhbmtfZRgN",
            "IAEoCSLJAQoUV29ybGRNYXBfQ29uZmlnX0RhdGESWAoVV29ybGRNYXBfQ29u",
            "ZmlnX2l0ZW1zGAEgAygLMjkuQ29uZmlnRGF0YS5Xb3JsZE1hcF9Db25maWdf",
            "RGF0YS5Xb3JsZE1hcENvbmZpZ0l0ZW1zRW50cnkaVwoYV29ybGRNYXBDb25m",
            "aWdJdGVtc0VudHJ5EgsKA2tleRgBIAEoDRIqCgV2YWx1ZRgCIAEoCzIbLkNv",
            "bmZpZ0RhdGEuV29ybGRNYXBfQ29uZmlnOgI4AUIjCiFjb20udHJpbml0aWdh",
            "bWVzLnNlcnZlci5jb25mLmF1dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ConfigData.WorldMap_Config), global::ConfigData.WorldMap_Config.Parser, new[]{ "Id", "BankDefault", "ConditionA", "BankA", "ConditionB", "BankB", "ConditionC", "BankC", "ConditionD", "BankD", "ConditionE", "BankE" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ConfigData.WorldMap_Config_Data), global::ConfigData.WorldMap_Config_Data.Parser, new[]{ "WorldMapConfigItems" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WorldMap_Config : pb::IMessage<WorldMap_Config> {
    private static readonly pb::MessageParser<WorldMap_Config> _parser = new pb::MessageParser<WorldMap_Config>(() => new WorldMap_Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WorldMap_Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ConfigData.WorldMapConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldMap_Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldMap_Config(WorldMap_Config other) : this() {
      id_ = other.id_;
      bankDefault_ = other.bankDefault_;
      conditionA_ = other.conditionA_;
      bankA_ = other.bankA_;
      conditionB_ = other.conditionB_;
      bankB_ = other.bankB_;
      conditionC_ = other.conditionC_;
      bankC_ = other.bankC_;
      conditionD_ = other.conditionD_;
      bankD_ = other.bankD_;
      conditionE_ = other.conditionE_;
      bankE_ = other.bankE_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldMap_Config Clone() {
      return new WorldMap_Config(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    /// <summary>
    ///* 英雄id 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "bank_default" field.</summary>
    public const int BankDefaultFieldNumber = 3;
    private string bankDefault_ = "";
    /// <summary>
    ///* 默认库 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BankDefault {
      get { return bankDefault_; }
      set {
        bankDefault_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "condition_a" field.</summary>
    public const int ConditionAFieldNumber = 4;
    private string conditionA_ = "";
    /// <summary>
    ///* 条件a 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ConditionA {
      get { return conditionA_; }
      set {
        conditionA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bank_a" field.</summary>
    public const int BankAFieldNumber = 5;
    private string bankA_ = "";
    /// <summary>
    ///* 新库a 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BankA {
      get { return bankA_; }
      set {
        bankA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "condition_b" field.</summary>
    public const int ConditionBFieldNumber = 6;
    private string conditionB_ = "";
    /// <summary>
    ///* 条件b 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ConditionB {
      get { return conditionB_; }
      set {
        conditionB_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bank_b" field.</summary>
    public const int BankBFieldNumber = 7;
    private string bankB_ = "";
    /// <summary>
    ///* 新库b 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BankB {
      get { return bankB_; }
      set {
        bankB_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "condition_c" field.</summary>
    public const int ConditionCFieldNumber = 8;
    private string conditionC_ = "";
    /// <summary>
    ///* 条件c 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ConditionC {
      get { return conditionC_; }
      set {
        conditionC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bank_c" field.</summary>
    public const int BankCFieldNumber = 9;
    private string bankC_ = "";
    /// <summary>
    ///* 新库c 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BankC {
      get { return bankC_; }
      set {
        bankC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "condition_d" field.</summary>
    public const int ConditionDFieldNumber = 10;
    private string conditionD_ = "";
    /// <summary>
    ///* 条件d 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ConditionD {
      get { return conditionD_; }
      set {
        conditionD_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bank_d" field.</summary>
    public const int BankDFieldNumber = 11;
    private string bankD_ = "";
    /// <summary>
    ///* 新库d 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BankD {
      get { return bankD_; }
      set {
        bankD_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "condition_e" field.</summary>
    public const int ConditionEFieldNumber = 12;
    private string conditionE_ = "";
    /// <summary>
    ///* 条件e 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ConditionE {
      get { return conditionE_; }
      set {
        conditionE_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bank_e" field.</summary>
    public const int BankEFieldNumber = 13;
    private string bankE_ = "";
    /// <summary>
    ///* 新库e 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BankE {
      get { return bankE_; }
      set {
        bankE_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WorldMap_Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WorldMap_Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (BankDefault != other.BankDefault) return false;
      if (ConditionA != other.ConditionA) return false;
      if (BankA != other.BankA) return false;
      if (ConditionB != other.ConditionB) return false;
      if (BankB != other.BankB) return false;
      if (ConditionC != other.ConditionC) return false;
      if (BankC != other.BankC) return false;
      if (ConditionD != other.ConditionD) return false;
      if (BankD != other.BankD) return false;
      if (ConditionE != other.ConditionE) return false;
      if (BankE != other.BankE) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (BankDefault.Length != 0) hash ^= BankDefault.GetHashCode();
      if (ConditionA.Length != 0) hash ^= ConditionA.GetHashCode();
      if (BankA.Length != 0) hash ^= BankA.GetHashCode();
      if (ConditionB.Length != 0) hash ^= ConditionB.GetHashCode();
      if (BankB.Length != 0) hash ^= BankB.GetHashCode();
      if (ConditionC.Length != 0) hash ^= ConditionC.GetHashCode();
      if (BankC.Length != 0) hash ^= BankC.GetHashCode();
      if (ConditionD.Length != 0) hash ^= ConditionD.GetHashCode();
      if (BankD.Length != 0) hash ^= BankD.GetHashCode();
      if (ConditionE.Length != 0) hash ^= ConditionE.GetHashCode();
      if (BankE.Length != 0) hash ^= BankE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (BankDefault.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BankDefault);
      }
      if (ConditionA.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ConditionA);
      }
      if (BankA.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BankA);
      }
      if (ConditionB.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ConditionB);
      }
      if (BankB.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(BankB);
      }
      if (ConditionC.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ConditionC);
      }
      if (BankC.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(BankC);
      }
      if (ConditionD.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(ConditionD);
      }
      if (BankD.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(BankD);
      }
      if (ConditionE.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(ConditionE);
      }
      if (BankE.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(BankE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (BankDefault.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BankDefault);
      }
      if (ConditionA.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConditionA);
      }
      if (BankA.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BankA);
      }
      if (ConditionB.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConditionB);
      }
      if (BankB.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BankB);
      }
      if (ConditionC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConditionC);
      }
      if (BankC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BankC);
      }
      if (ConditionD.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConditionD);
      }
      if (BankD.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BankD);
      }
      if (ConditionE.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConditionE);
      }
      if (BankE.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BankE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WorldMap_Config other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.BankDefault.Length != 0) {
        BankDefault = other.BankDefault;
      }
      if (other.ConditionA.Length != 0) {
        ConditionA = other.ConditionA;
      }
      if (other.BankA.Length != 0) {
        BankA = other.BankA;
      }
      if (other.ConditionB.Length != 0) {
        ConditionB = other.ConditionB;
      }
      if (other.BankB.Length != 0) {
        BankB = other.BankB;
      }
      if (other.ConditionC.Length != 0) {
        ConditionC = other.ConditionC;
      }
      if (other.BankC.Length != 0) {
        BankC = other.BankC;
      }
      if (other.ConditionD.Length != 0) {
        ConditionD = other.ConditionD;
      }
      if (other.BankD.Length != 0) {
        BankD = other.BankD;
      }
      if (other.ConditionE.Length != 0) {
        ConditionE = other.ConditionE;
      }
      if (other.BankE.Length != 0) {
        BankE = other.BankE;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 26: {
            BankDefault = input.ReadString();
            break;
          }
          case 34: {
            ConditionA = input.ReadString();
            break;
          }
          case 42: {
            BankA = input.ReadString();
            break;
          }
          case 50: {
            ConditionB = input.ReadString();
            break;
          }
          case 58: {
            BankB = input.ReadString();
            break;
          }
          case 66: {
            ConditionC = input.ReadString();
            break;
          }
          case 74: {
            BankC = input.ReadString();
            break;
          }
          case 82: {
            ConditionD = input.ReadString();
            break;
          }
          case 90: {
            BankD = input.ReadString();
            break;
          }
          case 98: {
            ConditionE = input.ReadString();
            break;
          }
          case 106: {
            BankE = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class WorldMap_Config_Data : pb::IMessage<WorldMap_Config_Data> {
    private static readonly pb::MessageParser<WorldMap_Config_Data> _parser = new pb::MessageParser<WorldMap_Config_Data>(() => new WorldMap_Config_Data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WorldMap_Config_Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ConfigData.WorldMapConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldMap_Config_Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldMap_Config_Data(WorldMap_Config_Data other) : this() {
      worldMapConfigItems_ = other.worldMapConfigItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldMap_Config_Data Clone() {
      return new WorldMap_Config_Data(this);
    }

    /// <summary>Field number for the "WorldMap_Config_items" field.</summary>
    public const int WorldMapConfigItemsFieldNumber = 1;
    private static readonly pbc::MapField<uint, global::ConfigData.WorldMap_Config>.Codec _map_worldMapConfigItems_codec
        = new pbc::MapField<uint, global::ConfigData.WorldMap_Config>.Codec(pb::FieldCodec.ForUInt32(8), pb::FieldCodec.ForMessage(18, global::ConfigData.WorldMap_Config.Parser), 10);
    private readonly pbc::MapField<uint, global::ConfigData.WorldMap_Config> worldMapConfigItems_ = new pbc::MapField<uint, global::ConfigData.WorldMap_Config>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<uint, global::ConfigData.WorldMap_Config> WorldMapConfigItems {
      get { return worldMapConfigItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WorldMap_Config_Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WorldMap_Config_Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!WorldMapConfigItems.Equals(other.WorldMapConfigItems)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= WorldMapConfigItems.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      worldMapConfigItems_.WriteTo(output, _map_worldMapConfigItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += worldMapConfigItems_.CalculateSize(_map_worldMapConfigItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WorldMap_Config_Data other) {
      if (other == null) {
        return;
      }
      worldMapConfigItems_.Add(other.worldMapConfigItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            worldMapConfigItems_.AddEntriesFrom(input, _map_worldMapConfigItems_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
